name: clinic_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc:
  flutter_screenutil:
  go_router:
  dio:
  flutter_secure_storage:
  get_it:
  easy_localization:
  carousel_slider:
  cached_network_image: ^3.3.1
  pull_down_button:
  infinite_scroll_pagination:
  video_player:
  youtube_player_flutter: ^8.1.2
  flutter_widget_from_html: ^0.9.1
  flutter_expandable_table: ^2.0.1
  material_text_fields: ^1.0.3
  debounce_textfield: ^0.0.2
  chips_choice: ^3.0.1
  easy_pdf_viewer: ^1.0.7
  syncfusion_flutter_xlsio: ^24.2.6
  flutter_svg: ^1.1.6
  flutter_staggered_grid_view: ^0.7.0
  bottom_sheet: ^4.0.1
  toggle_switch: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
    - assets/translations/

  fonts:
    - family: Lora
      fonts:
        - asset: fonts/lora/Lora-Bold.ttf
          weight: 700
        - asset: fonts/lora/Lora-SemiBold.ttf
          weight: 600
        - asset: fonts/lora/Lora-Medium.ttf
          weight: 500
        - asset: fonts/lora/Lora-Regular.ttf
          weight: 400
  
    - family: Lateef
      fonts:
        - asset: fonts/lateef/Lateef-Bold.ttf
          weight: 700
        - asset: fonts/lateef/Lateef-SemiBold.ttf
          weight: 600
        - asset: fonts/lateef/Lateef-Medium.ttf
          weight: 500
        - asset: fonts/lateef/Lateef-Regular.ttf
          weight: 400
  
    - family: NotoNaskhArabic
      fonts:
        - asset: fonts/notoNaskhArabic/NotoNaskhArabic-Bold.ttf
          weight: 700
        - asset: fonts/notoNaskhArabic/NotoNaskhArabic-SemiBold.ttf
          weight: 600
        - asset: fonts/notoNaskhArabic/NotoNaskhArabic-Medium.ttf
          weight: 500
        - asset: fonts/notoNaskhArabic/NotoNaskhArabic-Regular.ttf
          weight: 400